### ISSUE TITLE
[bug] color of hearthfire is.. blue?

### ISSUE THREAD

**Issue by rozzzly** [narenranjit/chandrian-theme#1]
what to do? what to do?

![](https://i.giphy.com/media/l0MYIDlXCD0wFS2Yg/giphy.webp)

**Comment by narenranjit** [comment]
May be brush up on your literary fantasy ;) 

http://kingkiller.wikia.com/wiki/The_Chandrian

> Each of the Chandrian is believed to have a specific sign associated with them, through which one can tell if they are near. One of the most well-known of these is blue flame.

[From "The Kingkiller Chronicles", which I highly recommend if you're into those kinds of books]

**Comment by rozzzly** [comment]
Perhaps my gif was too subtle... Let me quote the same [wikia...](http://kingkiller.wikia.com/wiki/Chandrian,_Chandrian#cite_ref-tnotw3_0-1)

> When the **hearthfire** turns to **blue**,
> **What to do? What to do?**
> Run outside. Run and hide.

> When his eyes are black as crow?
> Where to go[...]

I saw the name of the theme and being a huge fan of the series, I though I'd pay homage with a surreptitious phony-bug report.

😜

**Comment by narenranjit** [comment]
Hah, that gif should've clued me in 🤦

Thanks for trying out the theme, I also take _actual_ bug reports and feature requests ;)
